# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sat Jul  7 00:45:25 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(838, 619)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/graphics/app_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layBasePath = QtGui.QHBoxLayout()
        self.layBasePath.setObjectName(_fromUtf8("layBasePath"))
        self.lblBasePath = QtGui.QLabel(MainWindow)
        self.lblBasePath.setObjectName(_fromUtf8("lblBasePath"))
        self.layBasePath.addWidget(self.lblBasePath)
        self.txtBasePath = QtGui.QLineEdit(MainWindow)
        self.txtBasePath.setObjectName(_fromUtf8("txtBasePath"))
        self.layBasePath.addWidget(self.txtBasePath)
        self.btnBrowse = QtGui.QPushButton(MainWindow)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.layBasePath.addWidget(self.btnBrowse)
        self.verticalLayout.addLayout(self.layBasePath)
        self.gbxOptions = QtGui.QGroupBox(MainWindow)
        self.gbxOptions.setObjectName(_fromUtf8("gbxOptions"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbxOptions)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkScanRecursive = QtGui.QCheckBox(self.gbxOptions)
        self.chkScanRecursive.setObjectName(_fromUtf8("chkScanRecursive"))
        self.horizontalLayout.addWidget(self.chkScanRecursive)
        self.chkUsePath = QtGui.QCheckBox(self.gbxOptions)
        self.chkUsePath.setObjectName(_fromUtf8("chkUsePath"))
        self.horizontalLayout.addWidget(self.chkUsePath)
        self.chkUseExtension = QtGui.QCheckBox(self.gbxOptions)
        self.chkUseExtension.setObjectName(_fromUtf8("chkUseExtension"))
        self.horizontalLayout.addWidget(self.chkUseExtension)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.gbxOptions)
        self.gbxRules = QtGui.QGroupBox(MainWindow)
        self.gbxRules.setMaximumSize(QtCore.QSize(16777215, 112))
        self.gbxRules.setObjectName(_fromUtf8("gbxRules"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.gbxRules)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.txtRules = QtGui.QTextEdit(self.gbxRules)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtRules.sizePolicy().hasHeightForWidth())
        self.txtRules.setSizePolicy(sizePolicy)
        self.txtRules.setAcceptRichText(False)
        self.txtRules.setObjectName(_fromUtf8("txtRules"))
        self.horizontalLayout_4.addWidget(self.txtRules)
        self.verticalLayout.addWidget(self.gbxRules)
        self.gbxFiles = QtGui.QGroupBox(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.gbxFiles.sizePolicy().hasHeightForWidth())
        self.gbxFiles.setSizePolicy(sizePolicy)
        self.gbxFiles.setObjectName(_fromUtf8("gbxFiles"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbxFiles)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tblFiles = RenameTable(self.gbxFiles)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblFiles.sizePolicy().hasHeightForWidth())
        self.tblFiles.setSizePolicy(sizePolicy)
        self.tblFiles.setAlternatingRowColors(True)
        self.tblFiles.setWordWrap(False)
        self.tblFiles.setColumnCount(2)
        self.tblFiles.setObjectName(_fromUtf8("tblFiles"))
        self.tblFiles.setColumnCount(2)
        self.tblFiles.setRowCount(0)
        self.tblFiles.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tblFiles, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.gbxFiles)
        self.gbxStatus = QtGui.QGroupBox(MainWindow)
        self.gbxStatus.setObjectName(_fromUtf8("gbxStatus"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbxStatus)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblStatus = QtGui.QLabel(self.gbxStatus)
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.horizontalLayout_2.addWidget(self.lblStatus)
        self.verticalLayout.addWidget(self.gbxStatus)
        self.buttonBox = QtGui.QDialogButtonBox(MainWindow)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.lblBasePath.setBuddy(self.txtBasePath)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MainWindow.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MainWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BAON", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBasePath.setText(QtGui.QApplication.translate("MainWindow", "Base Path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.chkScanRecursive.setText(QtGui.QApplication.translate("MainWindow", "Recursively scan subfolders", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUsePath.setText(QtGui.QApplication.translate("MainWindow", "Use path", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUseExtension.setText(QtGui.QApplication.translate("MainWindow", "Use extension", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxRules.setTitle(QtGui.QApplication.translate("MainWindow", "Rename Rules", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxFiles.setTitle(QtGui.QApplication.translate("MainWindow", "Renamed Files", None, QtGui.QApplication.UnicodeUTF8))
        self.gbxStatus.setTitle(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("MainWindow", "Enter the base path for the files that are to be renamed.", None, QtGui.QApplication.UnicodeUTF8))

from gui.RenameTable import RenameTable
import resources_rc
