#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Fri Jan 27 22:35:32 2012

import wx
import sys

from gui.MainWindow import MainWindow

class BaonApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        main_window = MainWindow(None, -1, "")
        self.SetTopWindow(main_window)
        
        if len(sys.argv) > 1:
            main_window.setup(basePath = sys.argv[1])
        
        main_window.Show()
        return 1

# end of class BaonApp

if __name__ == "__main__":
    baon = BaonApp(0)
    baon.MainLoop()