#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Fri Jan 27 22:35:32 2012

import wx
from gui.MainWindow import MainWindow

class BaonApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        main_window = MainWindow(None, -1, "")
        self.SetTopWindow(main_window)
        main_window.Show()
        
        main_window.showFiles(["a","b","c"], ["d","e","f"])
        return 1

# end of class BaonApp

if __name__ == "__main__":
    baon = BaonApp(0)
    baon.MainLoop()