#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Mon Jan 23 22:48:58 2012

import wx
from MainWindow import MainWindow

if __name__ == "__main__":
    baon = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    main_window = MainWindow(None, -1, "")
    baon.SetTopWindow(main_window)
    main_window.Show()
    baon.MainLoop()
